serviceA-6539182:
    image: 'registry.cn-hangzhou.aliyuncs.com/jingshanlb/bluegreen-service-a:6539182'
    labels:
        aliyun.scale: 3
        aliyun.routing.port_5000: servicea.local
serviceB-de6e31f:
    image: 'registry.cn-hangzhou.aliyuncs.com/jingshanlb/bluegreen-service-b:de6e31f'
    environment:
        - 'dep_endpoint=http://servicea.local'
    labels:
        aliyun.scale: 2
        aliyun.routing.port_5001: serviceb
    external_links:
        - "servicea.local"
